# Generated by Django 3.2.6 on 2021-08-22 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='provider_response',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
