# Generated by Django 3.2.6 on 2021-08-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210822_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='Продано'),
        ),
    ]
