# Generated by Django 3.2.6 on 2021-09-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ad_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='sold',
            new_name='is_sold',
        ),
    ]
