# Generated by Django 3.2.6 on 2021-09-03 13:17

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_ad_ad_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ad'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=sorl.thumbnail.fields.ImageField(upload_to='uploads/ad_pics/'),
        ),
    ]
