# Generated by Django 3.2.6 on 2021-09-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210903_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='car',
            new_name='ad',
        ),
    ]
