# Generated by Django 3.2.6 on 2021-09-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_car_picture_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
